const whatsnew=[
{
    id:1,
    newslink:"https://example.com/pdfs/healthcare-report-2023.pdf"
},
{
    id:2,
    newslink:"https://example.com/pdfs/mental-health-awareness-guide.pdf"
},
{
    id:3,
    newslink:"https://example.com/pdfs/mental-health-awareness-guide.pdf"
},
{
    id:4,
    newslink:"https://example.com/pdfs/mental-health-awareness-guide.pdf"
},
{
    id:5,
    newslink:"https://example.com/pdfs/mental-health-awareness-guide.pdf"
},
{
    id:6,
    newslink:"https://example.com/pdfs/mental-health-awareness-guide.pdf"
},
{
    id:7,
    newslink:"https://example.com/pdfs/mental-health-awareness-guide.pdf"
},
{
    id:8,
    newslink:"https://example.com/pdfs/mental-health-awareness-guide.pdf"
},
{
    id:9,
    newslink:"https://example.com/pdfs/mental-health-awareness-guide.pdf"
},
{
    id:10,
    newslink:"https://example.com/pdfs/mental-health-awareness-guide.pdf"
},
]
export default whatsnew;